import * as THREE from 'three';
import { sanitizeVisualParams, visualPatchForPreset } from './VisualSettings.js';

const VERT = `varying vec2 vUv;void main(){vUv=uv;gl_Position=vec4(position.xy,0.,1.);}`;
const FRAG = `
precision highp float;
uniform sampler2D tDiffuse;uniform sampler2D tDepth;uniform vec2 uResolution;uniform float uTime;uniform float uNear;uniform float uFar;uniform vec3 uFogColor;uniform vec3 uHazeColor;uniform vec3 uSunDir;uniform float uVisuals;uniform float uPostFx;uniform float uFog;uniform float uFogDensity;uniform float uFogStart;uniform float uFogEnd;uniform float uHeightFog;uniform float uDistanceFog;uniform float uHaze;uniform float uSunHaze;uniform float uBloom;uniform float uBloomStrength;uniform float uBloomThreshold;uniform float uExposure;uniform float uGamma;uniform float uContrast;uniform float uSaturation;uniform float uTemperature;uniform float uTint;uniform float uCloudShadows;uniform float uCloudStrength;uniform float uCloudScale;uniform float uCloudSpeed;uniform float uCloudDir;uniform float uLightShafts;uniform float uShaftIntensity;uniform float uShaftLength;uniform float uShaftDecay;uniform float uVignette;uniform float uVignetteStrength;uniform float uGrain;uniform float uGrainStrength;uniform float uChromAb;uniform float uChromStrength;uniform float uAo;uniform float uAoStrength;uniform float uDebug;
varying vec2 vUv;
#include <packing>
float depthDist(vec2 uv){float z=texture2D(tDepth,uv).x;float vz=perspectiveDepthToViewZ(z,uNear,uFar);return min(-vz,uFar);} 
float hash(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);} 
float noise(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(hash(i),hash(i+vec2(1,0)),f.x),mix(hash(i+vec2(0,1)),hash(i+vec2(1,1)),f.x),f.y);} 
vec3 grade(vec3 c){c*=uExposure;c=max(c,vec3(0.));c=c/(c+vec3(1.));c=pow(c,vec3(1.0/max(uGamma,0.01)));c=mix(vec3(.5),c,uContrast);float l=dot(c,vec3(.299,.587,.114));c=mix(vec3(l),c,uSaturation);c.r+=uTemperature*.035-uTint*.02;c.b-=uTemperature*.035;c.g+=uTint*.025;return clamp(c,0.,1.);} 
void main(){vec2 uv=vUv;vec2 px=1./uResolution;vec3 col=texture2D(tDiffuse,uv).rgb;float dist=depthDist(uv);float sky=step(uFar*.999,dist);
 if(uVisuals>.5){float df=smoothstep(uFogStart,uFogEnd,dist)*uDistanceFog;float hf=pow(1.-uv.y,1.8)*uHeightFog*smoothstep(60.,uFogEnd,dist);float hz=pow(smoothstep(.40,1.0,uv.y),1.7)*uHaze;float fog=clamp((df+hf)*uFog*uFogDensity*3.0,0.,.92);col=mix(col,uFogColor,fog*(1.-sky*.25));col=mix(col,uHazeColor,hz*.45);vec2 sUv=uv-vec2(.5+.35*uSunDir.x,.55+.28*uSunDir.y);float sun=pow(max(0.,1.-length(sUv)*2.2),2.0)*uSunHaze;col+=uHazeColor*sun*.25;
  if(uCloudShadows>.5){float a=uCloudDir;vec2 dir=vec2(cos(a),sin(a));float n=noise((uv+dir*uTime*uCloudSpeed)*uCloudScale*7.0)+.5*noise((uv-dir*uTime*uCloudSpeed*.7)*uCloudScale*15.0);float sh=smoothstep(.42,.82,n)*(1.-sky);col*=1.-sh*uCloudStrength;}
  if(uLightShafts>.5){vec2 sunPos=vec2(.5+.38*uSunDir.x,.58+.32*uSunDir.y);float ray=0.;vec2 delta=(sunPos-uv)*uShaftLength/8.;vec2 p=uv;float decay=1.;for(int i=0;i<8;i++){p+=delta;float occ=1.-smoothstep(0.,uFar*.98,depthDist(clamp(p,vec2(.001),vec2(.999))));ray+=occ*decay;decay*=uShaftDecay;}ray/=8.;col+=uHazeColor*ray*uShaftIntensity;}
 }
 if(uPostFx>.5){if(uAo>.5){float d0=dist;float edge=0.;edge+=abs(depthDist(uv+vec2(px.x,0.))-d0);edge+=abs(depthDist(uv+vec2(0.,px.y))-d0);float ao=1.-clamp(edge*.004,0.,1.)*uAoStrength;col*=ao;}if(uBloom>.5){vec3 b=vec3(0.);for(int x=-2;x<=2;x++){for(int y=-2;y<=2;y++){vec3 s=texture2D(tDiffuse,uv+vec2(float(x),float(y))*px*2.).rgb;b+=max(s-uBloomThreshold,0.);}}b/=25.;col+=b*uBloomStrength*2.0;}col=grade(col);if(uChromAb>.5){float r=texture2D(tDiffuse,uv+px*3.*uChromStrength*uResolution.x).r;float b=texture2D(tDiffuse,uv-px*3.*uChromStrength*uResolution.x).b;col.r=mix(col.r,r,.35);col.b=mix(col.b,b,.35);}if(uVignette>.5){float v=smoothstep(.95,.25,length(uv-.5));col*=mix(1.-uVignetteStrength,1.,v);}if(uGrain>.5){col+=(hash(uv*uResolution+uTime)-.5)*uGrainStrength;}}
 if(uDebug==1.) col=vec3(dist/uFar); else if(uDebug==2.) col=vec3(clamp((smoothstep(uFogStart,uFogEnd,dist)*uDistanceFog+pow(1.-uv.y,1.8)*uHeightFog)*uFogDensity,0.,1.)); else if(uDebug==3.) col=vec3(noise(uv*uCloudScale*7.0));
 gl_FragColor=vec4(clamp(col,0.,1.),1.);}`;

export class VisualsSystem {
  constructor(renderer, scene) {
    this.renderer = renderer; this.scene = scene; this.params = {}; this.worldMode = 'studio'; this.screenshotOverride = false;
    this._rt = null; this._depth = null; this._size = new THREE.Vector2();
    this._quadScene = new THREE.Scene(); this._quadCam = new THREE.OrthographicCamera(-1,1,1,-1,0,1);
    this._fogColor = new THREE.Color(); this._hazeColor = new THREE.Color();
    this._mat = new THREE.ShaderMaterial({ vertexShader: VERT, fragmentShader: FRAG, depthTest:false, depthWrite:false, uniforms: {
      tDiffuse:{value:null},tDepth:{value:null},uResolution:{value:new THREE.Vector2(1,1)},uTime:{value:0},uNear:{value:1},uFar:{value:1},uFogColor:{value:new THREE.Color()},uHazeColor:{value:new THREE.Color()},uSunDir:{value:new THREE.Vector3(0,1,0)},uVisuals:{value:1},uPostFx:{value:1},uFog:{value:1},uFogDensity:{value:.2},uFogStart:{value:100},uFogEnd:{value:2000},uHeightFog:{value:.2},uDistanceFog:{value:.4},uHaze:{value:1},uSunHaze:{value:.2},uBloom:{value:1},uBloomStrength:{value:.08},uBloomThreshold:{value:.8},uExposure:{value:1},uGamma:{value:2.2},uContrast:{value:1},uSaturation:{value:1},uTemperature:{value:0},uTint:{value:0},uCloudShadows:{value:0},uCloudStrength:{value:.1},uCloudScale:{value:1},uCloudSpeed:{value:.02},uCloudDir:{value:0},uLightShafts:{value:0},uShaftIntensity:{value:.2},uShaftLength:{value:.7},uShaftDecay:{value:.9},uVignette:{value:0},uVignetteStrength:{value:.2},uGrain:{value:0},uGrainStrength:{value:.03},uChromAb:{value:0},uChromStrength:{value:.001},uAo:{value:1},uAoStrength:{value:.12},uDebug:{value:0}
    }});
    const geo = new THREE.BufferGeometry(); geo.setAttribute('position', new THREE.BufferAttribute(new Float32Array([-1,-1,0,3,-1,0,-1,3,0]),3)); geo.setAttribute('uv', new THREE.BufferAttribute(new Float32Array([0,0,2,0,0,2]),2)); this._quadScene.add(new THREE.Mesh(geo,this._mat));
  }
  applyParams(params, worldMode='studio') { this.worldMode = worldMode; this.params = sanitizeVisualParams(params, worldMode); this._syncUniforms(); }
  applyPreset(preset) { return visualPatchForPreset(preset, this.worldMode); }
  setScreenshotOverride(enabled) { this.screenshotOverride = !!enabled; }
  isActive() { const p=this.params; return !!(p.visualsEnabled && (p.atmosphereEnabled || p.postFxEnabled || p.visualDebugView !== 'off')); }
  _ensureTarget(scale=1) { this.renderer.getDrawingBufferSize(this._size); const w=Math.max(1,Math.floor(this._size.x*scale)), h=Math.max(1,Math.floor(this._size.y*scale)); if(this._rt&&this._rt.width===w&&this._rt.height===h)return; this.disposeTarget(); this._depth=new THREE.DepthTexture(w,h); this._depth.type=THREE.UnsignedShortType; this._rt=new THREE.WebGLRenderTarget(w,h,{depthTexture:this._depth,depthBuffer:true}); this._mat.uniforms.uResolution.value.set(w,h); }
  _syncUniforms(){const p=this.params,u=this._mat.uniforms; this._fogColor.set(p.fogColor); this._hazeColor.set(p.hazeColor); u.uFogColor.value.copy(this._fogColor); u.uHazeColor.value.copy(this._hazeColor); u.uVisuals.value=p.visualsEnabled&&p.atmosphereEnabled?1:0; u.uPostFx.value=p.visualsEnabled&&p.postFxEnabled?1:0; u.uFog.value=p.fogEnabled?1:0; u.uFogDensity.value=p.fogDensity; u.uFogStart.value=p.fogStart; u.uFogEnd.value=p.fogEnd; u.uHeightFog.value=p.heightFogStrength+(p.volumetricFogEnabled?.18:0); u.uDistanceFog.value=p.distanceFogStrength; u.uHaze.value=p.horizonHaze?1:0; u.uSunHaze.value=p.sunHazeStrength; u.uBloom.value=p.bloomEnabled?1:0; u.uBloomStrength.value=p.bloomStrength; u.uBloomThreshold.value=p.bloomThreshold; u.uExposure.value=p.exposure; u.uGamma.value=p.gamma; u.uContrast.value=p.contrast; u.uSaturation.value=p.saturation; u.uTemperature.value=p.temperature; u.uTint.value=p.tint; u.uCloudShadows.value=p.cloudShadowsEnabled?1:0; u.uCloudStrength.value=p.cloudShadowStrength; u.uCloudScale.value=p.cloudShadowScale; u.uCloudSpeed.value=p.cloudShadowSpeed; u.uCloudDir.value=THREE.MathUtils.degToRad(p.cloudShadowDirection); u.uLightShafts.value=p.lightShaftsEnabled?1:0; u.uShaftIntensity.value=p.lightShaftIntensity; u.uShaftLength.value=p.lightShaftLength; u.uShaftDecay.value=p.lightShaftDecay; u.uVignette.value=p.vignette?1:0; u.uVignetteStrength.value=p.vignetteStrength; u.uGrain.value=p.filmGrain?1:0; u.uGrainStrength.value=p.filmGrainStrength; u.uChromAb.value=p.chromaticAberration?1:0; u.uChromStrength.value=p.chromaticAberrationStrength; u.uAo.value=p.aoEnabled?1:0; u.uAoStrength.value=p.aoStrengthPost; u.uDebug.value={off:0,depth:1,fog:2,cloudShadows:3}[p.visualDebugView]??0; }
  render(scene,camera,time=0,sunDir=null){ if(!this.isActive()){this.renderer.render(scene,camera);return;} const p=this.params; const scale=this.screenshotOverride ? Math.max(p.visualRenderScale,p.screenshotRenderScale) : p.visualRenderScale; this._ensureTarget(scale); this._syncUniforms(); const u=this._mat.uniforms; u.uTime.value=time; u.uNear.value=camera.near; u.uFar.value=camera.far; if(sunDir)u.uSunDir.value.copy(sunDir); this.renderer.setRenderTarget(this._rt); this.renderer.clear(); this.renderer.render(scene,camera); this.renderer.setRenderTarget(null); u.tDiffuse.value=this._rt.texture; u.tDepth.value=this._depth; this.renderer.render(this._quadScene,this._quadCam); }
  disposeTarget(){ if(this._rt){this._rt.dispose(); this._rt=null;} if(this._depth){this._depth.dispose(); this._depth=null;} }
  dispose(){ this.disposeTarget(); this._mat.dispose(); const mesh=this._quadScene.children[0]; mesh?.geometry?.dispose(); }
}
